### ISSUE TITLE
Synse plugin needed for Chamber carousel

### ISSUE THREAD

**Issue by hulksmaaash** [vapor-ware/synse-modbus-ip-plugin#30]
The carousel operates via Modbus over IP, so we need to create a plugin to allow for portal control via Synse Server.

**Comment by edaniszewski** [comment]
@hulksmaaash the modbus-ip plugin was shown to work with the lab carousel simulator, so I think this issue can be closed as we already have a plugin for it. it'll just need to be configured, but we already have the register mapping for it, so its pretty trivial
